mode: auto

#å¤´åƒ
avatar:
  url: /images/avatar.png # ä½ çš„å¤´åƒå›¾ç‰‡åœ°å€
  rounded: true
  opacity: 1
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/alipay-qrcode.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/wechatpay-qrcode.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/youarequeen/youarequeen.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: ["nick"]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: youarequeen/youarequeen.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light



engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia


google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012


albums:
  enable: true

girls:
  enable: true

tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: "#21374b"
  å­¦ä¹ : saddlebrown
  MAD: crimson
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: "#0078e7"
  éšç¬”: mediumpurple
  Blender: "#d04d2d"
  Linux: "#2577b1"
  ä¸­ä¼ : "#ccb44b"
  éƒ¨è½: "#DD306A"
  ç§‘å¹»: midnightblue
  èš‚èšæ£®æ—: "#54a892"

categories:
  äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L



say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: QQ ç¾¤ 
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://qm.qq.com
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/YunYouJun
    icon: icon-github-line
    color: "#6e5494"
  - name: å¾®åš
    link: https://weibo.com/
    icon: icon-weibo-line
    color: "#E6162D"
  - name: è±†ç“£
    link: https://www.douban.com
    icon: icon-douban-line
    color: "#007722"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: å¾®ä¿¡å…¬ä¼—å·
    link: 
    icon: icon-wechat-2-line
    color: "#1AAD19"
  - name: Twitter
    link: https://twitter.com
    icon: icon-twitter-line
    color: "#1da1f2"
  # - name: Telegram
  #   link: https://t.me
  #   icon: icon-telegram-line
  #   color: "#0088CC"
  - name: Telegram Channel
    link: https://t.me
    # icon: icon-telegram-fill
    icon: icon-telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: imzjl@vip.qq.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: Travelling
    link: https://travellings.link
    icon: icon-train-line
    color: black

